mintdjango/mintbuilderapp/urls.py
from django.urls import path

from . import views, bot

app_name = "mintbuilderapp"
urlpatterns = [
    path("", views.index_view, name='index'),
    path("helloworld/", views.select_button_view, name='hw_view'),
    path("clear-section/", views.clear_section, name='clear_section'),
    path("<int:chat_id>/<int:group_id>", views.detail, name="detail"),
    path("<int:chat_id>/new_request", views.new_request, name="new_request"),
    path("<int:chat_id>/<int:group_id>/add_participant/", views.add_participant, name="add_participant"),
    path("<int:chat_id>/<int:group_id>/remove_participant/", views.remove_participant, name="remove_participant"),
    path("<int:chat_id>/<int:group_id>/edit_poll_param/", views.edit_poll_param, name="edit_poll_param"),
    path("<int:chat_id>/init", views.initialize, name="init"),
    path("<int:chat_id>/teams", views.generate_teams, name="teams"),
    path("<int:chat_id>/reroll_teams", views.reroll_teams, name="reroll_teams"),
    path("<int:chat_id>/post_teams", bot.post_teams, name="post_teams"),
    path("<int:chat_id>/result", views.result, name="result"),
    path("<int:chat_id>/<int:group_id>/button_unselected/", views.unselect_button_view, name='but_unselect'),
    path("<int:chat_id>/<int:group_id>/button_selected/", views.select_button_view, name='but_select'),
    # path("<int:chat_id>/<int:group_id>/button_selected_locked/", views.select_lock_button_view, name='but_select_lock'),
]

mintdjango/mintdjango/urls.py
from django.contrib import admin
from django.urls import include, path
import debug_toolbar
urlpatterns = [
    path("mintbuilderapp/", include("mintbuilderapp.urls")),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls))
]

mintdjango/mintbuilderapp/models.py
import random
import math

from django.db import models
from django.contrib import admin

# Create your models here.


class Poll(models.Model):
    chat_id = models.BigIntegerField()
    poll_id = models.BigIntegerField(default=0)
    message_id = models.BigIntegerField(default=0)
    chat_name = models.CharField(max_length=200)
    team_size = models.IntegerField(default=6)
    max_participant = models.IntegerField(default=12)
    is_telegram =models.BooleanField(default=False)

    def last_group(self):
        groups = list(self.group_set.all().order_by('tab_position'))
        if len(groups) == 0:
            return 0
        else:
            return groups[-1].tab_position

    def teams_created(self):
        for team in self.team_set.all():
            if team.number_of_participants() > 0:
                return True
        return False

    def teamsize_respected(self):
        if self.team_set.count() > math.ceil(self.participant_set.count() / self.team_size):
            return False
        for team in self.team_set.all():
            if team.number_of_participants() > self.team_size:
                return False
        return True

    def request_respected(self):
        for group in self.group_set.all():
            request = list(group.participant_set.all())
            for i, part1 in enumerate(request):
                for part2 in request[i:]:

                    if part1.team_in_poll(self) != part2.team_in_poll(self):
                        return False
        return True

    def participants_to_string(self):
        first_names = set()
        homonyms = set()
        for member in self.participant_set.all():
            first_name = member.participant_name
            if first_name in first_names:
                homonyms.add(first_name)
            else:
                first_names.add(first_name)
        name_dict = {}
        for member in self.participant_set.all():
            first_name = member.participant_name
            if first_name in homonyms:
                last_name = member.surname if member.surname else member.username if member.username else "X"
                name_dict[member.pk] = first_name + " " + last_name
            else:
                name_dict[member.pk] = first_name
        return name_dict

    @admin.display(
        ordering='chat_name',
        description="Number of participants"
    )
    def number_of_participants(self):
        return self.participant_set.count()

    def __str__(self):
        return self.chat_name


class Team(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

    @admin.display(
        description="Number of participants"
    )
    def number_of_participants(self):
        return self.participant_set.count()


class Group(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    color = models.CharField(max_length=20, default='zinc')
    tab_position = models.IntegerField(default=0)

    def pick_color(self, other_groups):
        cols = ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky',
                'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose']
        random.shuffle(cols)
        while True:
            col = cols.pop(0)
            other_cols = [other_group.color for other_group in other_groups]
            if col not in other_cols:
                break
            if len(cols) == 0:
                col = 'slate'
                break
        self.color = col
        self.save()

    def request(self):
        return list(self.participant_set.all())

    @admin.display(
        ordering='color',
        description="Number of participants"
    )
    def number_of_participants(self):
        return self.participant_set.count()

    def __str__(self):
        return self.color


class Participant(models.Model):
    poll = models.ManyToManyField(Poll)
    team = models.ManyToManyField(Team)
    group = models.ManyToManyField(Group)
    participant_name = models.CharField(max_length=200)
    participant_id = models.BigIntegerField(default=0)
    surname = models.CharField(max_length=200, default=None, null=True)
    username = models.CharField(max_length=200, default=None, null=True)
    verbose = models.BooleanField(default=False)

    @admin.display(
        ordering='participant_name',
        description="Number of poll answered"
    )
    def number_of_polls(self):
        return self.poll.count()

    def group_in_poll(self, poll: Poll):
        group = filter(lambda gr: gr in poll.group_set.all(), self.group.all())
        l = list(group)
        if len(l) == 0:
            return None
        else:
            assert len(l) == 1
            return l[0]

    def team_in_poll(self, poll: Poll):
        team = filter(lambda t: t in poll.team_set.all(), self.team.all())
        l = list(team)
        if len(l) == 0:
            return None
        else:
            assert len(l) == 1
            return l[0]

    def is_telegram(self):
        return self.participant_id != 0

    def __str__(self):
        return self.participant_name

mintdjango/mintbuilderapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound
from django.template.response import TemplateResponse

from .common.util.homonym import teams_to_string
from .models import Poll, Participant, Team, Group
from .common.util.team import random_team_generator

# Create your views here.


def index_view(request):
    return render(request, 'mintbuilderapp/index.html', {"name": 'user1', "color": 'teal'})


def select_button_view(request, chat_id, group_id):
    user_id = int(request.POST.get('button_unselected'))
    user = get_object_or_404(Participant, pk=user_id)
    poll = get_object_or_404(Poll, pk=chat_id)
    group = get_object_or_404(Group, pk=group_id)
    # Check if user is in no group
    # (important for concurrency i.e. the user has been added in a group by another request)
    if not user.group_in_poll(poll):
        user.group.add(group)
        user.save()
        message = {}
    else:
        message = {'message' : 'Un autre utilisateur a fait une modification qui a annulé la vôtre'}
    to_render = detail(request, chat_id, group_id)
    if message:
        to_render.context_data.update(message)
    # print(to_render.context_data)
    return to_render #detail(request, chat_id, group_id)


def unselect_button_view(request, chat_id, group_id):
    user_id = int(request.POST.get('button_selected'))
    user = get_object_or_404(Participant, pk=user_id)
    poll = get_object_or_404(Poll, pk=chat_id)
    # unselect user
    group = get_object_or_404(Group, pk=group_id)
    # Check if user is indeed in the targeted group
    # (important for concurrency i.e. the user has been removed from a group by another request)
    if user.group_in_poll(poll) == group:
        group.participant_set.remove(user)
    return detail(request, chat_id, group_id)


# group_id is group.pk
def detail(request, chat_id, group_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    # Remove tabs of empty groups by defaulting the group to zinc and putting it at the end of the list of groups
    for group in poll.group_set.all():
        if group.number_of_participants() == 0 and group.color != 'zinc' and group.pk != group_id:
            group.color = 'zinc'
            group.tab_position = poll.last_group() + 1
            group.save()
    groups = poll.group_set.all().order_by('tab_position')
    group = get_object_or_404(Group, pk=group_id)
    # group is the tab on which we are. If it is an empty group, it will be zinc. A color is picked for the group
    if group.color == 'zinc':
        group.pick_color(groups)
    part_groups = [(participant, participant.group_in_poll(poll))
                   for participant in poll.participant_set.all().order_by('participant_name', 'surname')]
    return TemplateResponse(request, "mintbuilderapp/detail.html",
                            {"poll": poll,
                             "group": group,
                             "part_groups": part_groups,
                             "part_names": poll.participants_to_string()})


def add_participant(request, chat_id, group_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    user_name = request.POST.get('new_participant')
    parse_name = user_name.split(' ')
    first_name = parse_name[0]
    last_name = " ".join(parse_name[1:])
    null_participants = Participant.objects.filter(poll=None)
    # If there is no "empty" participant
    if len(null_participants) == 0:
        new_participant = Participant.objects.create(participant_name=first_name, participant_id=0)
        if last_name:
            new_participant.surname = last_name
        else:
            homonyms = Participant.objects.filter(participant_name=first_name)
            for i in range(homonyms.count() + 1):
                default_name = '#' + str(i)
                if homonyms.filter(surname=default_name).count() == 0:
                    new_participant.surname = default_name
        poll.participant_set.add(new_participant)
        new_participant.save()
    # If there is a participant with no poll, we overwrite them
    else:
        new_participant = null_participants[0]
        new_participant.poll.clear()
        poll.participant_set.add(new_participant)
        new_participant.participant_name = first_name
        if last_name:
            new_participant.surname = last_name
        else:
            homonyms = Participant.objects.filter(participant_name=first_name)
            for i in range(homonyms.count() + 1):
                default_name = '#' + str(i)
                if homonyms.filter(surname=default_name).count() == 0:
                    new_participant.surname = default_name
        new_participant.participant_id = 0
        new_participant.save()
    message = {}
    if poll.number_of_participants() > poll.max_participant:
        message = {'message': "Attention, il y a maintenant {} personnes qui viennent alors que la limite de places "
                             "est {}".format(poll.number_of_participants, poll.max_participant)}
    to_render = detail(request, chat_id, group_id)
    if message:
        to_render.context_data.update(message)
    return to_render  # detail(request, chat_id, group_id)


def remove_participant(request, chat_id, group_id):
    user_id = int(request.POST.get("confirm_delete_but"))
    try:
        user_todelete = Participant.objects.get(pk=user_id)
    except Participant.DoesNotExist:
        return
    poll = get_object_or_404(Poll, pk=chat_id)
    group = user_todelete.group_in_poll(poll)
    user_todelete.group.remove(group)
    team = user_todelete.team_in_poll(poll)
    user_todelete.team.remove(team)
    user_todelete.poll.remove(poll)
    user_todelete.save()
    return detail(request, chat_id, group_id)


def edit_poll_param(request, chat_id, group_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    new_max = request.POST.get('max_participant')
    new_size = request.POST.get('team_size')
    poll.max_participant = new_max
    poll.team_size = new_size
    poll.save()
    return detail(request, chat_id, group_id)


def new_request(request, chat_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    # Look for first zinc (empty) group
    for group in poll.group_set.all().order_by('tab_position'):
        if group.color == 'zinc':
            return detail(request, chat_id, group.pk)
    # If too many request (17)
    if poll.group_set.count() > 17:
        message = {
            'message': "Attention, la limite du nombre de requête est atteinte. "
                       "Impossible de créer une nouvelle requête".format()}
        group = poll.group_set.all().order_by('tab_position')
        to_render = detail(request, chat_id, group[0].pk)
        to_render.context_data.update(message)
        return to_render
    else:
        new_group = Group.objects.create(poll=poll, tab_position=poll.last_group() + 1)
        return detail(request, chat_id, new_group.pk)


def initialize(request, chat_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    for i, group in enumerate(poll.group_set.all()):
        group.color = 'zinc'
        group.tab_position = i
        group.participant_set.clear()
        group.save()
    return new_request(request, chat_id)



def generate_teams(request, chat_id):
    '''
    Generate teams if they don't exist already or if they are not valid
    '''
    poll = get_object_or_404(Poll, pk=chat_id)
    teams = poll.team_set.all()
    participants = poll.participant_set.all()
    # If some requests or the teams size are not respected, clear the team then roll them
    if not poll.request_respected() or not poll.teamsize_respected():
        clear_teams(chat_id)

    # If a request is larger than the team sizes
    largest_group_size = max([group.participant_set.count() for group in poll.group_set.all()])
    if largest_group_size >= poll.team_size:
        group_id = request.POST.get("roll")
        message = {'message': "Attention, il y a une requête de {} personnes qui viennent alors que la taille des équipes "
                              "est {}".format(largest_group_size, poll.team_size)}
        to_render = detail(request, chat_id, group_id)
        to_render.context_data.update(message)
        return to_render

    # If teams are already rolled, show them as is
    if not poll.teams_created():
        requests = [group.request() for group in poll.group_set.all()]
        teams_created = random_team_generator(participants, groupements=requests, max_per_team=poll.team_size)
        to_create = len(teams_created)-len(teams)
        # Create new teams if there aren't enough
        if to_create > 0:
            for _ in range(to_create):
                Team.objects.create(poll=poll)
        teams = poll.team_set.all() # prob useless with postgres
        # Populate teams with the result of random_team_generator
        for team, team_created in zip(teams, teams_created):
            for team_member in team_created:
                team.participant_set.add(team_member)
            team.save()
    teams = [team.participant_set.all() for team in poll.team_set.all() if team.participant_set.count() > 0]
    teams_string = teams_to_string(teams)
    return render(request, "mintbuilderapp/teams.html", {"poll": poll, "teams": teams_string})


def clear_teams(chat_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    teams = poll.team_set.all()
    for team in teams:
        team.participant_set.clear()
        team.save()


def reroll_teams(request, chat_id):
    clear_teams(chat_id)
    return generate_teams(request, chat_id)


def clear_section(request):
    return HttpResponse("")


def result(request, chat_id):
    poll = get_object_or_404(Poll, pk=chat_id)
    return render(request, "mintbuilderapp/result.html", {"poll": poll})

mintdjango/mintbuilderapp/templates/mintbuilderapp/detail.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Mint Builder</title>
        <script src="https://unpkg.com/htmx.org@2.0.4"
                integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
                crossorigin="anonymous">
        </script>
        <script src="https://unpkg.com/hyperscript.org@0.9.14"></script>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    {% load mint_extras %}
    <body class="bg-gradient-to-r from-lime-300 via-emerald-300 to-teal-300 text-emerald-800 font-sans p-8"
          id="detail"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <div class="container mx-auto text-center">
        <h2 class="text-3xl font-semibold mb-4">Let's Mint some Teams</h2>
        <button name="team_param"
                _="on click trigger showModal on #edit_param"
                class="bg-gradient-to-r from-lime-500 via emerald-500 to-teal-500 hover:bg-gradient-to-br text-white text-lg font-bold py-2 px-4 mb-3 rounded-full">
            {{ poll.chat_name }}
        </button>
        <dialog id="edit_param"
                style="opacity: 0;"
                _= "on showModal call my showModal() then transition my opacity to 1 over 150ms
                    on click measure me then
                    set is_in_me to result.top <= event.clientY and
                                    event.clientY <= result.top + result.height and
                                    result.left <= event.clientX and
                                    event.clientX <= result.left + result.width
                    if is_in_me is false trigger closeModal end
                    on closeModal transition my opacity to 0 over 150ms then call my close() "
                class="center w-4/5 bg-transparent">
            <form name="edit_param_form"
                  method="dialog"
                  hx-post='{% url "mintbuilderapp:edit_poll_param" poll.pk group.pk %}'
                  hx-target="#detail"
                  class="bg-green-200 shadow-md rounded px-6 pt-4 pb-6 mb-4">
                <div>
                    <div class="grid gap-y-2 grid-cols-3">
                        <div class="col-span-2">
                            <label class="object-left mb-4" for="max_participant">Places disponibles:</label>
                        </div>
                        <div class="col-span-1">
                            <input type="number"
                               id="max_participant"
                               name="max_participant"
                               class="object-right"
                               min="1"
                               max="999"
                               value="{{ poll.max_participant }}">
                        </div>
                        <div class="col-span-2">
                            <label class="object-left mb-4" for="team_size">Taille des équipes:</label>
                        </div>
                        <div class="col-span-1">
                            <input type="number"
                               id="team_size"
                               name="team_size"
                               class="object-right"
                               min="1"
                               max="999"
                               value="{{ poll.team_size }}">
                        </div>
                    </div>
                    <br>
                    <input type="submit"
                           class="center bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
                           _="on click trigger closeModal on #edit_param">
                </div>
            </form>
        </dialog>
        {% if message %}
            <dialog open
                    id="alert-dialog"
                    style="transition: all 150ms ease-in; opacity: 0;"
                    class="center w-4/5"
                    _=" on load transition my opacity to 1
                        then wait for click or 1.5s
                        then transition my opacity to 0 then settle then remove me">
                <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md"
                     role="alert">
                    {{ message }}
                </div>
            </dialog>
        {% endif %}
        <div name="tablist" class="grid grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7 2xl:grid-cols-8">
            {% for poll_group in poll.group_set.all|dictsort:"tab_position" %}
                {% if poll_group.color != 'zinc' %}
                    <button name="tab"
                            hx-get='{% url "mintbuilderapp:detail" poll.pk poll_group.pk %}'
                            hx-target="#detail"
                            hx-swap="outerHTML"
                            class="bg-{{ poll_group.color }}-500 hover:bg-{{ poll_group.color }}-700 text-white font-bold py-2 px-4">
                        {% if poll_group.color == 'emerald' %}
                            <em> mint </em>
                        {% else %}
                            {{ poll_group }}
                        {% endif %}
                    </button>
                {% endif %}
            {% endfor %}
            {% if group.number_of_participants > 0 %}
            <button name="new_tab"
                    hx-post='{% url "mintbuilderapp:new_request" poll.pk %}'
                    hx-target="#detail"
                    hx-swap="outerHTML"
                    class="bg-emerald-600 hover:bg-emerald-800 text-white font-bold py-2 px-4">
                +
            </button>
            {% endif %}
        </div>
        <div class="mb-4 rounded-sm rounded-t-none border border-{{ group.color }}-500 ">
        {% for participant, part_group in part_groups %}
            {% if part_group and part_group.pk != group.pk %}
                {% include "mintbuilderapp/partials/button_selected_locked.html" with participant=participant color=part_group.color to_group=part_group %}
            {% elif participant in group.participant_set.all %}
                {% include "mintbuilderapp/partials/button_selected.html" with participant=participant color=group.color to_group=group %}
            {% elif not part_group and participant not in group.participant_set.all %}
                {% include "mintbuilderapp/partials/button_unselected.html" with participant=participant color=group.color to_group=group %}
            {% endif %}
        {% endfor %}
        <dialog id="confirm_delete"
                style="opacity: 0;"
                _= "on showModal set #confirm_delete_but's value to my @part_id
                    then put `Veux-tu vraiment supprimer ${my @part_name} ?`into #delete_label
                    then call my showModal() then transition my opacity to 1 over 150ms
                    on click measure me then
                    set is_in_me to result.top <= event.clientY and
                                    event.clientY <= result.top + result.height and
                                    result.left <= event.clientX and
                                    event.clientX <= result.left + result.width
                    if is_in_me is false trigger closeModal end
                    on closeModal transition my opacity to 0 over 150ms then call my close() "
                class="center w-4/5 bg-transparent">
            <form id="confirm_delete_form"
                  method="dialog"
                  hx-post='{% url "mintbuilderapp:remove_participant" poll.pk group.pk %}'
                  hx-target="#detail"
                  class="bg-green-200 shadow-md rounded px-6 pt-4 pb-6 mb-4">
                <output id="delete_label" class="mb-2">--</output><br>
                <button name="cancel_delete"
                        type="reset"
                        _="on click trigger closeModal on #confirm_delete"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                    Annuler
                </button>
                <button name="confirm_delete_but"
                        id="confirm_delete_but"
                        type="submit"
                        _="on click trigger closeModal on #confirm_delete"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                    Confirmer
                </button>
            </form>
        </dialog>
        <button name="add_participant"
                class="bg-transparent hover:bg-{{ group.color }}-500 text-{{ group.color }}-700 font-semibold hover:text-white py-2 px-4 mx-1 my-2 border border-{{ group.color }}-500 hover:border-transparent rounded"
                _="on click trigger showModal on #add_part_dialog">
            +
        </button>
        <dialog id="add_part_dialog"
                style="opacity: 0;"
                _= "on showModal call my showModal() then transition my opacity to 1 over 150ms
                    on click measure me then
                    set is_in_me to result.top <= event.clientY and
                                    event.clientY <= result.top + result.height and
                                    result.left <= event.clientX and
                                    event.clientX <= result.left + result.width
                    if is_in_me is false trigger closeModal end
                    on closeModal transition my opacity to 0 over 150ms then call my close() "
                class="center w-4/5 bg-transparent">
            <form name="add_part_form"
                  method="dialog"
                  hx-post='{% url "mintbuilderapp:add_participant" poll.pk group.pk %}'
                  hx-target="#detail"
                  class="bg-green-200 shadow-md rounded px-6 pt-4 pb-6 mb-4">
                <label class="mb-2" for="new_participant">Nom du participant:</label><br>
                <input type="text"
                       id="new_participant"
                       name="new_participant"
                       class="mb-4">
                <input type="submit"
                       class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
                       _="on click trigger closeModal on #add_part_dialog">
            </form>
        </dialog>
        </div>
        <div class="flex flex-col items-center">
            <button name="roll"
                    hx-post='{% url "mintbuilderapp:teams" poll.pk %}'
                    hx-target="#detail"
                    hx-swap="outerHTML"
                    value="{{ group.pk }}"
                    class="w-3/5 bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 border-b border-teal-700 rounded-t">
                Créer Équipes
            </button>
            <button name="réinit"
                        hx-put='{% url "mintbuilderapp:init" poll.pk %}'
                        hx-target="#detail"
                        hx-swap="outerHTML"
                        class="w-3/5 bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-b">
                    Réinitialiser
            </button>
        </div>
    </div>

</body>
</html>

mintdjango/mintbuilderapp/templates/mintbuilderapp/helloworld.html
<button hx-put=""
        hx-target="this"
        hx-swap="outerHTML"
        class="bg-{{ color }}-500 hover:bg-{{ color }}-700 text-white font-bold py-2 px-4 rounded">{{ name }}</button>

mintdjango/mintbuilderapp/templates/mintbuilderapp/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Task Management App</title>
        <script src="https://unpkg.com/htmx.org@2.0.4"
                integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
                crossorigin="anonymous">
        </script>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gradient-to-r from-purple-600 via-pink-600 to-red-600 text-white font-sans p-8">
    {% csrf_token %}
    <div class="container mx-auto text-center">
        <h2 class="text-3xl font-semibold mb-4">Ready to Get Started?</h2>
        <p class="mt-4">Join us today and experience the future of web development.</p>
        {% include "mintbuilderapp/partials/button_unselected.html" %}
    </div>
</body>
</html>

mintdjango/mintbuilderapp/templates/mintbuilderapp/result.html
<form action="{% url 'mintbuilderapp:teams' poll.chat_id %}" method="post">
    {% csrf_token %}
    <h1>{{ poll.chat_name }}</h1>
    {% for team in poll.team_set.all %}
    {% if team.participant_set.all %}
    <h3> Team {{ forloop.counter }} </h3>
    <ul>
        {% for part in team.participant_set.all %}
        <li> {{ part.participant_name }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endfor %}
    <input type="submit" value="Reroll">
</form>